sudo: required

services:
  - docker

env:
  matrix:
    - DOCKERFILE="Dockerfile-alpine" DOCKERPATH="2.4"

before_script:
  - docker version

script:
  - docker build -f ./${DOCKERPATH}/${DOCKERFILE} -t ${DOCKERPATH} ./${DOCKERPATH}

after_script:
  - docker images
